# Generated by Django 4.2.2 on 2023-08-07 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fencomment',
            options={'ordering': ['date_time_of_publication']},
        ),
    ]
