# Generated by Django 4.2.2 on 2023-07-16 16:52

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FenPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fen', models.CharField(validators=[django.core.validators.RegexValidator('[\\d/pnbrqkPNBRQK]+ [wb] [QKqk\\-]{1,4} [\\-abcdefgh12345678]{1,2} [\\d]{1,2} [\\d]{1,2}')])),
                ('evaluation', models.FloatField(blank=True, null=True)),
                ('is_a_puzzle', models.BooleanField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
