# Generated by Django 4.2.2 on 2023-07-18 18:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fenreader', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fenposition',
            name='fen',
            field=models.CharField(validators=[django.core.validators.RegexValidator('[\\d/pnbrqkPNBRQK]+ [wb] [QKqk\\-]{1,4} [\\-a-h1-8]{1,2} [\\d]{1,2} [\\d]{1,2}')]),
        ),
    ]
