# Generated by Django 4.2.2 on 2023-07-20 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fenreader', '0002_alter_fenposition_fen'),
    ]

    operations = [
        migrations.AddField(
            model_name='fenposition',
            name='black_player',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fenposition',
            name='tournament',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fenposition',
            name='white_player',
            field=models.CharField(blank=True, null=True),
        ),
    ]
