# Generated by Django 4.2.2 on 2023-08-08 18:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fenreader', '0004_fenposition_black_rating_fenposition_white_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='fenposition',
            name='best_line',
            field=models.CharField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(300)]),
        ),
    ]
