# Generated by Django 4.2.2 on 2023-08-09 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fenreader', '0006_remove_fenposition_evaluation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fenposition',
            name='best_line',
        ),
    ]
