# Generated by Django 4.2.2 on 2023-08-09 08:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fenreader', '0007_remove_fenposition_best_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='fenposition',
            name='best_lines',
            field=models.CharField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(300)]),
        ),
    ]
