# Generated by Django 4.2.2 on 2023-08-16 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fenreader', '0008_fenposition_best_lines'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fenposition',
            name='best_lines',
        ),
        migrations.CreateModel(
            name='EngineLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation', models.FloatField()),
                ('line', models.CharField()),
                ('to_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fenreader.fenposition')),
            ],
        ),
    ]
