# Generated by Django 4.2.2 on 2023-08-16 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fenreader', '0009_remove_fenposition_best_lines_engineline'),
    ]

    operations = [
        migrations.AddField(
            model_name='engineline',
            name='rank',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
