# Generated by Django 4.2.2 on 2023-08-16 10:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fenreader', '0010_engineline_rank'),
    ]

    operations = [
        migrations.CreateModel(
            name='PGN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pgn_moves', models.CharField()),
                ('white_name', models.CharField(blank=True, null=True)),
                ('white_rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(800), django.core.validators.MaxValueValidator(4000)])),
                ('black_player', models.CharField(blank=True, null=True)),
                ('black_rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(800), django.core.validators.MaxValueValidator(4000)])),
                ('tournament', models.CharField(blank=True, null=True)),
            ],
        ),
    ]
