# Generated by Django 4.2.2 on 2023-08-16 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fenreader', '0014_alter_pgn_pgn_moves'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pgn',
            name='pgn_moves',
            field=models.CharField(),
        ),
    ]
