# Generated by Django 4.2.2 on 2023-09-11 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fenreader', '0020_customgame_delete_customgames'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customgame',
            old_name='moves_pgn',
            new_name='moves_uci',
        ),
    ]
