# Generated by Django 4.2.2 on 2023-08-25 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chessanalyticsuser',
            name='piece_preference',
            field=models.CharField(default='cburnett'),
        ),
    ]
