# Generated by Django 4.2.2 on 2023-08-26 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_chessanalyticsuser_piece_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='chessanalyticsuser',
            name='notation_preference',
            field=models.CharField(default='uci'),
        ),
    ]
